TorrServ/Controllers/MainPathsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TorrServCore;
using TorrServData.Models;

namespace TorrServ.Controllers
{
    public class MainPathsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public MainPathsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [Authorize(Roles = "admin")]
        public IActionResult Index()
        {
            var sourcePaths = _unitOfWork.sourceOfMovies.ToList();

            return View(sourcePaths);
        }

        [Authorize(Roles = "admin")]
        public IActionResult Create() => View();
        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> Create(SourceOfMovies model)
        {
            if (model!=null)
            {
                SourceOfMovies newPath = new SourceOfMovies { path = model.path, Id = model.Id };
                _unitOfWork.sourceOfMovies.Add(newPath);
                await _unitOfWork.SaveAsync();
                return RedirectToAction("Index");
            }
            else
            return View(model);
        }

        public IActionResult Edit(Guid Id)
        {
            SourceOfMovies path =_unitOfWork.sourceOfMovies.GetById(Id);
            if (path == null)
            {
                return NotFound();
            }

            SourceOfMovies model = new SourceOfMovies { Id = path.Id, path = path.path };
            return View(model);
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(SourceOfMovies model)
        {
            if (ModelState.IsValid)
            {
                SourceOfMovies editPath = _unitOfWork.sourceOfMovies.GetById(model.Id); 
                if (editPath != null)
                {
                    editPath.path = model.path;
                    editPath.Id = model.Id;                    
                    await _unitOfWork.SaveAsync();
                    return RedirectToAction("Index");
                }
                else return NotFound();
            }
            else return View(model);



        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> Delete(Guid Id)
        {
            SourceOfMovies path = _unitOfWork.sourceOfMovies.GetById(Id);
            if (path != null)
            {
                _unitOfWork.sourceOfMovies.Delete(Id);
                await _unitOfWork.SaveAsync();
            }

            return RedirectToAction("Index");
        }

    }
}

TorrServ/Views/MainPaths/Create.cshtml
@model TorrServData.Models.SourceOfMovies
@{
    ViewBag.Title = "Add Path";
}

<form asp-action="Create" asp-controller="MainPaths">
    <div asp-validation-summary="All" class="btn-dark"></div>
    <div class="form-group btn-dark">
        <label asp-for="path" class="custom-control-label">Path</label>
        <input type="text" asp-for="path" class="form-control" />
    </div>    
    <div class="form-group btn-dark">
        <input type="submit" value="Add" class="btn btn-secondary" />
    </div>
</form>

TorrServ/Views/MainPaths/Edit.cshtml
@model TorrServData.Models.SourceOfMovies
@{
    ViewBag.Title = "Edit Path";
}

    <form asp-action="Edit" asp-controller="MainPaths">
        <div asp-validation-summary="All" class="btn-dark"></div>
        <div class="form-group">
            <input type="hidden" asp-for="Id" />
        </div>
        <div class="form-group">
            <h1>Currently Path @Model.path </h1>
        </div>
        <div class="form-group">
            <label asp-for="path" class="text-white">path</label>
            <input type="text" asp-for="path" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-dark" />
        </div>
    </form>

TorrServ/Views/MainPaths/Index.cshtml
@model IEnumerable<TorrServData.Models.SourceOfMovies>
@{
    ViewBag.Title = "List of users ";
}

<h2 class="text-white">List of users</h2>
<table class="table text-white">
    @foreach (var path in Model)
    {
        <tr>
            <td>@path.path</td>

            <td>
                <form asp-action="Delete" asp-route-Id="@path.Id" method="post">
                    <a class="btn btn-dark" asp-action="Edit" asp-route-id="@path.Id">ChangePath</a>                    
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
    }
</table>
<a class="btn badge-dark" asp-action="Create">AddPath</a>